### ISSUE TITLE
The QR code keep loading 

### ISSUE THREAD

**Issue by ravikant-pal** [pillaisravani3/free-otp-service#2]
Hi @pillaisravani3,

I'm using your service for OTP.
I tried to link my phone but it keeps loading it happens after clicking on the regenerate button

find below SS

<img width="1461" alt="image" src="https://github.com/pillaisravani3/free-otp-service/assets/53791094/87b8d79c-1c44-438f-88a2-25653c45755e">

Please help

**Comment by dearirshad2** [comment]
Fixed
